site_name: laminas-config-aggregator-modulemanager
docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
site_description: 'laminas/laminas-modulemanager extension for the laminas/laminas-config-aggregator package.'
repo_url: 'https://github.com/laminas/laminas-config-aggregator-modulemanager'
